error occured-
ubuntu 12.04
python 2.7
scrapy 0. some version
error: Exception error:the HtmlXPathSelector doesnt have the attribute XPath

Expected Solution:
Try to upgrade to ubuntu 14
try to install python 3.4